language: node_js
node_js: stable

before_install:
  - git config user.name "toughChow"
  - git config user.email "toughChow@gmail.com"
  - npm install -g hexo-cli

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - hexo clean
  - hexo generate

after_success:
  - cd ./public
  - git init
#  - sed -i "s/gh_token/c9035f33ff1cf855133720ae8d1980b754aa8e96/g" ./_config.yml
#  - sed -i'' "s~https://github.com/toughChow/toughChow.github.io.git~https://Travis-Hexo@github.com/toughChow/toughChow.github.io.git~" _config.yml
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://$GH@github.com/toughChow/toughChow.github.io.git" master:master
#  - hexo deploy
# E: Build LifeCycle

branches:
  only:
    - hexo
env:
 global:
   - GH_REF: github.com/toughChow/toughChow.github.io.git