language: node_js

node_js: stable

before_install:
  - npm install hexo-cli -g
  
# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - hexo clean
  - hexo g

after_script:
  - git clone https://${GH_REF} .deploy_git
  - cd .deploy_git
  - git checkout master
  - cd ../
  - mv .deploy_git/.git/ ./public/
  - cd ./public
  - git config --global user.name "toughChow"
  - git config --global user.email "toughChow@gmail.com"
  - git add .
  - git commit -m "Travis CI Auto Builder"
  - git push --force --quiet "https://$REPO_TOKEN@${GH_REF}" master:master
#  - cd ./public
#  - git init
#  - sed -i "s/gh_token/c9035f33ff1cf855133720ae8d1980b754aa8e96/g" ./_config.yml
#  - sed -i'' "s~https://github.com/toughChow/toughChow.github.io.git~https://Travis-Hexo@github.com/toughChow/toughChow.github.io.git~" _config.yml
#  - git add .
#  - git commit -m "Update docs"
#  - git push --force --quiet "https://$REPO_TOKEN@github.com/toughChow/toughChow.github.io.git" master:master
#  - hexo deploy
# E: Build LifeCycle

branches:
  only:
    - hexo
    
env:
 global:
   - GH_REF: github.com/toughChow/toughChow.github.io.git